python -u ./trains/multi_train.py \
  --data_folder ../../0_prepare_dataset/sequence/process_dataset/temp \
  --dest_folder ./model_output/ \
  --lr 0.0005 \
  --batch_size 256 \
  --epochs 30 \
  --device 1 \
  --if_std 0 \
  --model MTF_2 \
  --mode all \
  --layer_num 2 \
  --num_heads 4 \
  --emb_dim 50 \
  --graph_emb 32 \
  --graph_folder ../../0_prepare_dataset/graph/results/new_graph_dataset \
